services:
  frontend:
    build:
      context: ./frontend
    container_name: call-review-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
  backend:
    build: ./backend
    container_name: call-review-backend
    ports:
      - "8000:8000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - BACKEND_CORS_ORIGINS = ${BACKEND_CORS_ORIGINS}

    restart: always
